### ISSUE TITLE
upload file 10Mo

### ISSUE THREAD

**Issue by NicolasImberty** [eblondel/ownCloud4R#10]
Hello,

It's possible to upload file > 10Mo ?
It's make a error :
```
Error in owncloud$uploadFile(filename = "my_file",  : 
  WEBDAV - Error while uploading 'my_file' at 'my_url_owncloud'
```

**Comment by eblondel** [comment]
@NicolasImberty I believe you should consult first with your ownCloud provider if some limitation has been set-up.

**Comment by NicolasImberty** [comment]
I don't have limitation, I can upload file > 10 Mo manualy on onwcloud

**Comment by eblondel** [comment]
Yes, but they might have limited file size through the API. The API itself does not limit file size. I will give an attempt on my owncloud and let you know.

**Comment by eblondel** [comment]
@NicolasImberty i've tested upload of files of 10.5 Mb and ~ 40Mb and it worked; You should check your R code to make sure you point to an existing file, and check your Owncloud URL. If you think there is no issue with your code. You may want to check with your Owncloud administrator to see if they set-up a server limitation for upload file sizes.

**Comment by NicolasImberty** [comment]
Ok thank you.

**Comment by NicolasImberty** [comment]
For your information, there was server limitation for upload file sizes, my Owncloud administrator corrected.
