### ISSUE TITLE
uploadFile in a folder

### ISSUE THREAD

**Issue by NicolasImberty** [eblondel/ownCloud4R#9]
Hello

How could I upload a file which is in a folder without to move in this folder ?

For example :
`owncloud$uploadFile(filename = "Extraction/toto.csv", relPath = "destination")`
make a error because "Extraction" don’t exist in destination.

```
Setwd("Extractions")
owncloud$uploadFile(filename = "toto.csv", relPath = "destination")
```
It’s ok.

**Comment by eblondel** [comment]
Thanks @NicolasImberty i will look at this issue. This method is inherited from the Open Collaboration Service (OCS) R client at https://github.com/eblondel/ocs4R so if there is a fix it will be done there

**Comment by eblondel** [comment]
Fixed via https://github.com/eblondel/ocs4R/issues/6
Could reinstall ocs4R from Github and test?

**Comment by NicolasImberty** [comment]
It’s ok.
Thank you.
